### ISSUE TITLE
can not run this docker by "sh -c **"

### ISSUE THREAD

**Issue by snowy324** [doraTeX/Docker-clang9-objc2#1]
I was running it by this:
`docker run -it --rm -v /Users/bjhl/Documents/OnlineCode/packages/showmecode/data:/data doratex/clang9-objc2 sh -c "clang-objc -o hello /data/oc.m"`
here is the problem: 
`clang-objc: not found
`
help me pls!

**Comment by doraTeX** [comment]
@snowy324 
Since the `clang-objc` is an alias command defined in `/root/.bashrc` of the Docker container, it can be called only inside an interactive shell. Instead, by writing out its definition explicitly, you can launch the clang compiler with Objective-C libraries, as is shown in the following example.

```sh
$ docker run --rm \
 -v /Users/bjhl/Documents/OnlineCode/packages/showmecode/data:/data \
 doratex/clang9-objc2 \
 sh -c '. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh; ${CC} $(gnustep-config --objc-flags) $(gnustep-config --objc-libs) -fobjc-arc -lobjc -ldispatch -lgnustep-base -o hello /data/oc.m'
```

**Comment by snowy324** [comment]
> @snowy324
> Since the `clang-objc` is an alias command defined in `/root/.bashrc` of the Docker container, it can be called only inside an interactive shell. Instead, by writing out its definition explicitly, you can launch the clang compiler with Objective-C libraries, as is shown in the following example.
> 
> ```shell
> $ docker run --rm \
>  -v /Users/bjhl/Documents/OnlineCode/packages/showmecode/data:/data \
>  doratex/clang9-objc2 \
>  sh -c '. /usr/GNUstep/System/Library/Makefiles/GNUstep.sh; ${CC} $(gnustep-config --objc-flags) $(gnustep-config --objc-libs) -fobjc-arc -lobjc -ldispatch -lgnustep-base -o hello /data/oc.m'
> ```

ths my friend!
